apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: pg-storage
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/Users/gabriel.munera/Documents/KC/TrainingLab/localstorage/pg-db"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - training-cluster-1-control-plane
