apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /customer-app(/|$)(.*)
        backend:
          service:
            name: customer-app-svc
            port:
              number: 9090