apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
data:
  customer-app-pwd: bmltZGE=

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: db-env
  name: db-env
data:
  customer-app-dbname: customer-app-db
  customer-app-username: admin

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/gabriel.munera/Documents/KC/TrainingLab/localstorage/pg-db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  selector:
    app: pg
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pg
  name: pg
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - image: postgres:11
          name: pg
          ports:
          - containerPort: 5432       
          volumeMounts:
          - name: pg-volume
            mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: customer-app-dbname
                  name: db-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: customer-app-username
                  name: db-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: customer-app-pwd
                  name: db-secrets
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: pg-pvc